spring.application.name=DataMapping
#datasource configurations
spring.datasource.url=jdbc:mysql://localhost:3306/spring-database
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
# show SQL
spring.jpa.show-sql: true
# DDL generation
spring.jpa.generate-ddl=true
server.port=8989